name: debug test pandoc

on:
  push:
    branches: [ main ]
    paths:
      - '**/**'

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kjarosh/latex:2025.1-small

    steps:
    - name: Install dependencies
      run: |
        # Aggiungiamo gcompat per la compatibilità con binari glibc
        apk add --no-cache git bash tar python3 py3-pip pandoc gcompat gmp zlib
        pip install --break-system-packages pyyaml

    - name: Debug pandoc-crossref Dependencies
      run: |
        echo "--- Running dependency check on pandoc-crossref ---"
        # 1. Assicuriamoci che gli strumenti di diagnostica siano installati
        # 'ldd' si trova in 'musl-utils', wget per scaricare
        apk add --no-cache musl-utils wget
        
        # 2. Scarichiamo il binario di pandoc-crossref
        VERSION="0.3.17.0"
        URL="https://github.com/lierdakil/pandoc-crossref/releases/download/v${VERSION}/pandoc-crossref-linux-x86_64.tar.gz"
        wget -q $URL -O pandoc-crossref.tar.gz
        tar -xzf pandoc-crossref.tar.gz
        
        # 3. Eseguiamo ldd per vedere le dipendenze
        # Usiamo '|| true' per assicurarci che lo step non fallisca
        # anche se ldd restituisce un errore, così possiamo leggere l'output.
        ldd pandoc-crossref || true
        echo "--- End of dependency check ---"
