name: debug test pandoc

on:
  push:
    branches: [ main ]
    paths:
      - '**/**'

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kjarosh/latex:2025.1-small

    steps:
    - name: Install System & Build Dependencies
      run: |
        # Aggiungiamo gli strumenti per compilare Haskell: ghc e cabal-install
        # Aggiungiamo anche le librerie necessarie alla compilazione: gmp e zlib
        apk add --no-cache \
          git bash tar python3 py3-pip pandoc \
          ghc cabal-install gmp zlib
          
        pip install --break-system-packages pyyaml

    # --- NUOVO BLOCCO PER LA COMPILAZIONE CON CACHING ---
    - name: Cache and build pandoc-crossref from source
      uses: actions/cache@v4
      id: cache-pandoc-crossref
      with:
        # La chiave della cache include la versione. Se la cambi, la cache si invalida.
        key: pandoc-crossref-v0.3.17.0
        # Mettiamo in cache sia l'eseguibile finale sia i pacchetti di build di cabal
        path: |
          /usr/local/bin/pandoc-crossref
          ~/.cabal
    
    - name: Build and install pandoc-crossref if not cached
      if: steps.cache-pandoc-crossref.outputs.cache-hit != 'true'
      run: |
        echo "Cache not found. Compiling pandoc-crossref from source..."
        
        # Inizializziamo il database dei pacchetti di Cabal
        cabal update
        
        # Installiamo pandoc-crossref. Cabal gestirà il download e la compilazione.
        # Questo comando copierà l'eseguibile finale in ~/.cabal/bin/
        cabal install pandoc-crossref-0.3.17.0 --install-method=copy --overwrite-policy=always
        
        # Spostiamo l'eseguibile compilato in una cartella del PATH
        mv ~/.cabal/bin/pandoc-crossref /usr/local/bin/
        chmod +x /usr/local/bin/pandoc-crossref
        
        echo "pandoc-crossref compiled and installed successfully."

    - name: Verify pandoc-crossref installation
      run: |
        echo "Verifying pandoc-crossref..."
        pandoc-crossref --version
    # --- FINE DEL NUOVO BLOCCO ---
